name: Testing shop-automation-example

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Install deps
        run: poetry install
      - name: Run lint check
        run: poetry run pre-commit run --all-files
      - name: Install playwright
        run: poetry run playwright install chromium --with-deps
      - name: Run tests
        run: poetry run pytest

      - name: get allure history
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: allure report
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: publish allure
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
